### ISSUE TITLE
Use tools with either hand

### ISSUE THREAD

**Issue by Raicuparta** [Raicuparta/nomai-vr#178]
Poor left-handed people are suffering out there

**Comment by Raicuparta** [comment]
Switching the hand behavior in the game is very easy. The difficulty is switching the mappings...

**Comment by Swibles** [comment]
We are indeed suffering!

**Comment by Swibles** [comment]
Left handed people are suffering from being able to use their left hand for the signalscope :(

**Comment by artumino** [comment]
Added in 1.2.0
