### ISSUE TITLE
Can't exit in-game options menu (some times)

### ISSUE THREAD

**Issue by Raicuparta** [Raicuparta/nomai-vr#190]

**Comment by Raicuparta** [comment]
Seems to be caused by forcing the resolution. The save gets corrupted with no pickable resolutions, and user needs to pick a new resolution to fix it.

**Comment by Z5aI69A61** [comment]
I experience this after changing any graphics setting. Nothing I do allows me to exit.  
NomaiVR 0.35.1, game version 1.0.6.370 on Epic, Vive Pro.

**Comment by Raicuparta** [comment]
Closing as this doesn't seem to happen anymore. Not sure why.
