### ISSUE TITLE
Ice reflection only visible in one eye until player is very close

### ISSUE THREAD

**Issue by Raicuparta** [Raicuparta/nomai-vr#200]
Probably fixable only via shaders? If so, probably doomed.

**Comment by Anahkiasen** [comment]
Unless I'm mistaken I believe this is also happening to the tornadoes on Giant's Deep, or at least there's the same kind of eye-dependant reflections issues there

**Comment by Raicuparta** [comment]
@Anahkiasen Pretty sure it's the fog present in the planet.

**Comment by artumino** [comment]
Even though reflections are weird in VR the stereoscopic disparity should be fixed in the latest version, closing this for now
