### ISSUE TITLE
Controller oriented movement

### ISSUE THREAD

**Issue by Raicuparta** [Raicuparta/nomai-vr#266]

**Comment by QwertyUieo** [comment]
+1. Disabling head directional movement is all that is needed. Makes platforming difficult.

**Comment by Raicuparta** [comment]
@QwertyUieo That's a slightly different suggestion. Do you think aiming with the left hand would also make platforming difficult? Because then this means three different choices:

1. Head oriented movement;
2. Controller oriented movement;
3. Movement following only the analog stick input, nothing else.

I'm not sure I want to have so many options...

**Comment by yohaskan** [comment]
As a game of exploration, and not of "survival" (which reminds me of the locomotion system of The Solus Project. I liked being free Look/head to see the environment, while moving corps independently.
But i don't have finish all the game yet, perhaps some platforme passage a very tricky
By the way, you can see my progression in VR, if you want
(In french but subtitle in YT)
https://youtu.be/cJovV42uDa0

**Comment by Raicuparta** [comment]
@yohaskan nice videos :) Would appreciate if you could link to the mod in the description (either link to this repo or to www.outerwildsmods.com)

**Comment by yohaskan** [comment]
In the Youtube description? 
it's already there, but we only see the first three lines

**Comment by Raicuparta** [comment]
@yohaskan Ah I see it, sorry about that.

**Comment by yohaskan** [comment]
I have changed some text to see a little more

**Comment by QwertyUieo** [comment]
@Raicuparta I was suggesting your 3rd option. "Movement following only the analog stick input, nothing else." As @yohaskan suggested the game's focus is more on exploration. I feel that being able to view the environment while moving would be a nice feature to have.

**Comment by Raicuparta** [comment]
@QwertyUieo I see... The problem is that someone else suggested option 2. Option 3 is definitely easier to implement. I just don't like having too many options, especially options that conflict with each other. I'll have to think about it.

**Comment by Raicuparta** [comment]
Going with option 2 for now. I think it works pretty well and lets you easily look around while moving. Option will be available in next release (0.45)
