### ISSUE TITLE
Probe camera angles ?

### ISSUE THREAD

**Issue by yohaskan** [Raicuparta/nomai-vr#267]
How to change the orientation of the probe to take another camera angle in VR?

_(And with the Vive controllers, the indicators of the colored buttons are very confusing ; like press green button, but where??? and wich hand?)_

Great Mod by the way;)

**Comment by Raicuparta** [comment]
@yohaskan You should be able to rotate the probe by launching the probe, then touching the probe launcher with your left hand, while holding it with your right hand. No tutorial for that yet.

As for the buttons, it's not very easy to make it obvious in the game. You can go to SteamVR's input mapping settings for Outer Wilds and see the mappings there. Green is always the same as jump, blue is always the same as interact.

**Comment by yohaskan** [comment]
Ok thanks, i'll check that
