### ISSUE TITLE
HUD Scaling issue

### ISSUE THREAD

**Issue by QwertyUieo** [Raicuparta/nomai-vr#269]
When wearing the space suit or flying in the ship the HUD elements for navigation are not on the edge of the display. When using the space suit the in-game text is covered by the HUD unless you turn your head left and look with your eyes to the right.

**Comment by Raicuparta** [comment]
@QwertyUieo Would hiding the HUD during conversations be enough?

It's a bit tricky to scale the HUD in a way that works for every headset (because of the different FOVs each headset has, and the fact that I only have one headset to test with). But I could also try to add a setting to set the helmet HUD scale manually. What do you think?

**Comment by QwertyUieo** [comment]
@Raicuparta If you can add an X and Y offset in the nomai-vr options menu that would be best. If that is too challenging then disabling HUD in conversation would work but the HUD still blocks normal gameplay.

**Comment by senritsu** [comment]
I will take a look at providing an option for hiding the HUD in conversations, and if i get it working quickly i might try my hand at the offsets.

**Comment by Raicuparta** [comment]
`HelmetHUD.cs` has this line `surface.transform.localScale = Vector3.one * 3.28f;` which controls the scale of the HUD. Might be enough to make that `3.28f` configurable via mod options.

**Comment by senritsu** [comment]
I have a local branch which does just that, enabling a scale of 50% to 150%, now that config settings work again i will see if that is useful. From initial testing, at 150% it is considerably farther out of view, but still obscures dialogue bit, so i think those things are pretty different issues. Hiding the HUD solves conversations, a scale option might improve general usefulness of the HUD for certain HMDs.

**Comment by Raicuparta** [comment]
Sounds perfect.

And yes, the HUD scale will be just to adjust the HUD to the HMD, not related to the dialogue thing (since we will have a much better solution for that). Ideally we'd have some magic solution that checks the HMD's FOV and scales it accordingly, but it would be very hard to test.

**Comment by Raicuparta** [comment]
HUD scaling will be available in next version (0.54.0).
