### ISSUE TITLE
Error OWML after upgrade installation

### ISSUE THREAD

**Issue by yohaskan** [Raicuparta/nomai-vr#280]
After the Mod 0.46 upgrade
I have an 'OWML error' failed to locate local mod "path + cinema-camera.manifest \ manifest.json"

* Game Version: 
* OWML Version: 0.4.1
* NomaiVR Version: 0.46 (and 0.45 too)
* VR hardware: SSD

 
![outerwilds stat0807](https://user-images.githubusercontent.com/927744/86938189-6d0f2c00-c140-11ea-9e69-b24c5e7bcbfd.jpg)

**Comment by Raicuparta** [comment]
What the hell...

Can't seem to reproduce this. Does it happen every time you open the manager? This is almost definitely a bug in the Mod Manager. You can probably start the game fine and NomaiVR should work (and if it does't, I don't think this is the issue, check the logs).

**Comment by Raicuparta** [comment]
@yohaskan any any more info you could give me regarding what I asked?
