### ISSUE TITLE
Add ability to toggle tools visibility

### ISSUE THREAD

**Issue by Anahkiasen** [Raicuparta/nomai-vr#283]
It's very cool to have the tools around my belt, however a lot of the time when trying to take the scenery in, they take a significant portion of my view.

Is there still a button that has no binding that could be used to hide/show them on demand? Or an option to place them lower or something. It's particularly problematic when trying to land somewhere as if you look down, the tools obstruct greatly your view and it can become hard to see where you're landing.

**Comment by Raicuparta** [comment]
Good point, I often have this problem myself (but as the developer, I made myself believe it wasn't a big deal 😉).

I'm trying to think of a smart way to go about this. Having a dedicated button wouldn't work for a lot of VR controllers (just look at the Vive, that thing has like, no buttons at all). Maybe I could hide the tools unless the player's hand is close to them? So if you want them to disappear, you can just move your hand away from the belt? This would still be an option, toggleable through the mod options menu.

You also mentioned an option to place the tools lower. It's supposed to be a toolbelt, so waist height is what makes sense. Are they showing at an incorrect height for you? It's very likely that I just programmed it in a way that works for my own height. I've been meaning to add an option to configure the belt height, even if I implement the auto-hiding feature.

**Comment by Raicuparta** [comment]
@Anahkiasen Your feedback on my previous comment would be very helpful :)

**Comment by Anahkiasen** [comment]
I think only showing the tools when you get your hands close to them would be a nice natural way to handle it! Prevents having yet another button and should be very intuitive

**Comment by Raicuparta** [comment]
Not super happy with the way it turned out, but now there's an option for auto-hiding tools based on right hand distance. And also a setting for toolbelt height. Will be available in next release (0.54.0)

**Comment by Anahkiasen** [comment]
Nice! Eager to try it, thanks!
