### ISSUE TITLE
oculus rift touch controls issue?

### ISSUE THREAD

**Issue by sunnyalaska** [Raicuparta/nomai-vr#291]
thank you so much for all the hard work that went into this amazing mod!

i'm trying it out on my oculus rift, cv1. it looks amazing but i can't seem to get my touch controllers to work properly? there is a button for jump that works fine and i can pull out both tools from either side of my belt, but my motion mobility control doesn't work.  i'm assuming one joystick of an oculus touch controller is the camera view and the other is supposed to be for moving forward / back / left / right?  Both of my joysticks only seem to control the camera so you can basically only spin around in a circle but there's no way to move forward unless i physically walk to a different part of my room in real life. i have gone to the controls input menu but when i click on the "bindings" button, nothing happens, so it appears i can't rebind the control. does anyone have any advise?

thank you! i'm so thrilled that this beautiful game is in VR!

**Comment by Raicuparta** [comment]
Hi @sunnyalaska 

The "bindings" button in the menu is supposed to open the SteamVR input bindings menu. Strange that it isn't working for you, but can't say I'm too surprised (SteamVR can be very unpredictable).

Can you try to open the SteamVR input bindings menu yourself and see if everything looks correct? As if, see if the left analog stick is set to "move" and the right one set to "look".

You can open SteamVR settings from the little SteamVR pop-up window that shows up.

**Comment by sunnyalaska** [comment]
hola, thank you so much for getting back to me. I'm just seeing this
message now. I will try that and get back to you later today. I'm really
excited to get the game working.

All the best!

**Comment by sunnyalaska** [comment]
hello again!

so i did as you suggested, opened up the steam vr bindings directly and
everything is as is should be with one stick set to look and the other
stick set to move, yet when i play the game both sticks are set to look so
i can spin around but i can not move forward / back or sideways. i also
noticed that even though the triggers are supposed to be set for rocket
boost (and that is what the steam vr bindings show), however when i'm
trying to play the game they also seem to cause me to spin around as if
they are also binded to look?

i've tried to unbind and rebind every thing and i still get the same
results.  i've also tried to bind both joysticks to be Look and
conversely have binded both joysticks to be Move but that also makes no
difference.  any ideas?

i'm using the mod launcher program to launch the game and am only using the
vr mod. any ideas?

thank you for your help!

-steven
:)

**Comment by Raicuparta** [comment]
@sunnyalaska try these:

1. Make sure you don't have any other controllers connected besides your VR  stuff. If you do, disconnect them and test the game before trying the next step.

2. Try creating a new profile in the game and see if that one works.

3.  Make sure Mod Manager has the setting "Verbose Mode". Launch the game and look at the logs that OWML console prints on the black window. Show me what the logs say (either screenshot or copy paste here).

**Comment by sunnyalaska** [comment]
Ricardo, i will try that! your message reminds me of an additional thing
that may have caused the problem... i may have had the following situation
going on when i installed and tried to play the game the first time... i
had dual usb flight sticks plugged in to my pc as well as a an xbox style
joystick and the battery in one of my oculus touch controllers was dead and
i had to replace it when i first tried to play the game.. maybe the combo
of all the above or maybe if it only saw controller it somehow assigned the
same binding to the other one after i put a battery in it? since then i
have tried it with not other joysticks plugged in, but no luck. i think i
will unistall the mod loader, unistall the program from steam, reinstall
the program, reinstall the vr mod launcher, and if problems persist i will
try steps 2 and 3 and get back to you

btw its very thoughtful of you to be so generous with your time to
correspond with me in this way.  i very much appreciate you.

as a small token, here is an album of ambient, spacey, peaceful electric
guitar music I composed, played, recorded. perhaps you'll enjoy? i stared
at paintings / photos and tried to express the visual art musically.

https://stevenbacon.bandcamp.com/album/strange-loops-vol-1

if you like it and want to download it, just click buy and enter 0.00 and
it will be free and you won't be prompted for a card or any personal info,
it should just start the download of tunes. or you can listen for free on
line. or just ignore it all together! but again thank you.

-steven bacon

**Comment by sunnyalaska** [comment]
hola again,

I finally got it working! wow, what an amazing vr experience,
definitely the coolest vr game i've played to date.

the removing the joysticks didn't work but i did a few other things, not
sure what fixed it.

1. there was a new outer wilds update, so i installed that.
2. i noticed i had a logitech joystick app running in background so i
closed that.
3. i took your advice from last email and ran it in verbose mode and
created a new profile. it looks like i had never created a profile before
but i still let me start the game?
4. oculus had an update for the rift and controllers so i installed that.

i think what did it was creating a profile but not sure? thanks again! it's
a beautiful game and in vr it's epic. i fell off a tower and i actually
felt adrenaline and the sense of falling. it was amazing.

all the best!
-steven
:)
