### ISSUE TITLE
Mod will not initialize OpenVR

### ISSUE THREAD

**Issue by villain749** [Raicuparta/nomai-vr#329]
1.0.7.463, from the epic games store
0.71
0.53.0
Valve Index

 I cannot get the mod to work it fails to initaialize SteamVR. Here is a snippit of console output
```
Game files copied.	OWML	
Found mods:	OWML	
* Alek.EnableDebugMode v0.2	OWML	
* Raicuparta.NomaiVR v0.53.0	OWML	
Warning - Made for old version of OWML: v0.6.1	OWML	
PermanentManager.Awake is already patched.	OWML	
Raicuparta.NomaiVR requires VR.	OWML	
Successfully patched globalgamemanagers.	OWML	
Starting game...	OWML	
Client disconnected from console	Mod Manager	
Client connected to console	Mod Manager	
Mod loader has been initialized.	OWML	
For detailed log, see Logs/OWML.Log.03-08-2020-23.36.12.txt	OWML	
Game version: 1.0.7.463	OWML	
Start NomaiVR	NomaiVR	
NullReferenceException: Object reference not set to an instance of an object. Stack trace: NomaiVR.NomaiVR.InitSteamVR () NomaiVR.NomaiVR.Start ()	Unity	
In EnableDebugMode!
```

After the error the game launches as it normally would. The "Mods" menu shows the "nomai-vr" section but nothing is in VR. SteamVR is working well on my machine and I tried it without SteamVR running as per the instructions, and also with it already running but it didn't work.

**Comment by Raicuparta** [comment]
Hi @villain749 

I just released version 0.54.0. Can you check if the problem still happens?

**Comment by villain749** [comment]
Just tried it, unfortunatly I got the same result. Its the same error with the same stack trace. I did see it logged something about the toolbelt height. 

thanks for looking into this so quickly

**Comment by Raicuparta** [comment]
Not sure what could be wrong. Usually the Epic store version is easier to deal with... Some people have had luck adding Epic's executable to Steam's library, then right clicking -> properties -> show in VR library. Maybe that helps?

**Comment by SirXen0** [comment]
Not a bug, it's because you have Home Theater enabled for non-vr supported games. I had the same error as you but a friend pointed that out to me. 
![40479944 2449999_image](https://user-images.githubusercontent.com/14849378/89715322-79083b00-d9d7-11ea-8de5-a6271db6d71a.png)

**Comment by Raicuparta** [comment]
@SirXen0 thanks for the help. The only reason I didn't suggest this is because I thought this only affected users who own the game on Steam. Do you own it on Steam or Epic?

@villain749 I guess if have the Epic version but have Steam running, this might be the cause of the error? In which case please let me know, so I can add this info to the readme.

**Comment by SirXen0** [comment]
@Raicuparta On Steam, it kept having the issue and launched into theatre mode, but when I unchecked it in Steam settings, it launched into VR (and oh my goodness it's amazing in VR).

**Comment by villain749** [comment]
I appriciate all the suggestions, unforturnatly I could not get it to work. I tried adding the EpicLauncher, mod manager, owml, and the game to steam and adding it to the VR library. I tried unchecking the Desktop theater mode.  I tried older versions. I reinstalled SteamVR, I moved the installation drive.  I set everything up on a completly different computer but nothing seems to work. That same error. 
`NullReferenceException: Object reference not set to an instance of an object. Stack trace: NomaiVR.NomaiVR.InitSteamVR () NomaiVR.NomaiVR.Start ()` . So I decided to buy it on steam... It booted right up no problem. I am going to try to get a refund for the epic version. I did notice that the game version is 1.0.7.463 on the epic version, and 1.0.7.481 on steam.  Thanks again for taking the time to troubleshoot this with me. I'm off to to explore the galaxy.

**Comment by Raicuparta** [comment]
> I appriciate all the suggestions, unforturnatly I could not get it to work. I tried adding the EpicLauncher, mod manager, owml, and the game to steam and adding it to the VR library. I tried unchecking the Desktop theater mode. I tried older versions. I reinstalled SteamVR, I moved the installation drive. I set everything up on a completly different computer but nothing seems to work. That same error.
> `NullReferenceException: Object reference not set to an instance of an object. Stack trace: NomaiVR.NomaiVR.InitSteamVR () NomaiVR.NomaiVR.Start ()` . So I decided to buy it on steam... It booted right up no problem. I am going to try to get a refund for the epic version. I did notice that the game version is 1.0.7.463 on the epic version, and 1.0.7.481 on steam. Thanks again for taking the time to troubleshoot this with me. I'm off to to explore the galaxy.

Damn, you must be the first person I see who has less problems with Steam version than Epic. Glad you could make it work. I'm gonna leave this issue open for now, in case someone else finds it, and I'll look into what could cause this problem. Doubt I can do much about it though. Have fun!

**Comment by Raicuparta** [comment]
Since it doesn't seem like I'm gonna be finding a solution to this any time soon, my "fix" is to crash the game with a warning and suggest a list of possible fixes, including disabling game theater and buying the game in another store 🤷‍♀️
