### ISSUE TITLE
Trackerd 1 failed - Startup Error

### ISSUE THREAD

**Issue by SpideryYoda** [Raicuparta/nomai-vr#334]
* Game Version: 0.7.3
* OWML Version: 0.5.1
* NomaiVR Version: 0.55.0
* VR hardware: Valve Index

Mod updated to version 0.55.0 and will now not start. Gives below error in pop up and logs:

Trackerd 1 failed If you want to ignore this error and start the game anyway, edit NomaiVR/config.json, find "bypassFatalErrors", and set "value" to true. But be aware that this will likely face a lot of problems.

**Comment by Raicuparta** [comment]
hi @SpideryYoda  Please check the latest release (0.55.1)

Closed by cf7199a1c31f0058be17012d530ae53cec0ef7fd
