### ISSUE TITLE
Right Hand B Inputs Not Registering

### ISSUE THREAD

**Issue by DeFishe** [Raicuparta/nomai-vr#373]
Right hand B inputs on my Index controllers are consistently not working. For example, most of the time I can't ride the lift to the launch pad. Most of the time I can't put on my space suit. Most of the time I can't exit my space ship. Etc. It happens so frequently, that the game is unplayable for me.

I don't have steps to reproduce because the default state seems to be "not working". 

I recently updated from v0.58 which was working well, so a recent change might have caused this.

* Game Version: 1.0.7.481
* OWML Version: 0.7.3
* NomaiVR Version: 1.0
* VR hardware: Valve Index, Index Controllers
 
Side Note: I am getting unity errors in the logs every time I start the game. Are those expected?

**Comment by Raicuparta** [comment]
This is because the game is registering right hand grip being pressed, limitation of the input mappings on this mod, sorry. Try holding the controller in a way that prevents accidentally triggering the right hand grip, or go into SteamVR know mappings and change the sensitivity of the grip.

**Comment by DeFishe** [comment]
Oh, that makes sense. Its not immediately apparent this is happening. It would be nice if there was some sort of indication showing you are triggering the grip button. Or, at very least, a tool tip telling you to watch out for this. Maybe if the player holds the grip button for an inordinate amount of time you can flash a message like "It seems you have been holding the grip button for a long time. Do you mean to do this?" I'm sure I'm not going to be the only Index user with this issue. 

Anyway, its just a thought. I'm going to close the ticket since this isn't a bug.

**Comment by Raicuparta** [comment]
Yeah I couldn't figure out a good way to do this yet. Thanks for the suggestions!
