### ISSUE TITLE
On loading the game appears as a screen within the VR space within an auditorium

### ISSUE THREAD

**Issue by duggsy69** [Raicuparta/nomai-vr#380]
On loading the game appears as a screen within the VR space within an auditorium, so I'm looking at a flat screen from within this auditorium space and the controllers aren't functional.

Clearly set something up wrong, so any advice welcome.

Cheers

**Comment by Raicuparta** [comment]
That's SteamVR theatre mode. Right click the game on steam, properties, disable steam theatre.

**Comment by Raicuparta** [comment]
Hey @duggsy69, did you try my suggestion?

**Comment by duggsy69** [comment]
Hi there, yes I did, thanks your suggestion. When we disable theatre mode nothing at all shows up in the headset. We did this within the steam dialogue box for the game.

Any thoughts?

**Comment by Raicuparta** [comment]
Are you starting the game via the Mod Manager? Check the Logs tab for errors.

**Comment by Raicuparta** [comment]
Closing for lack of information
