### ISSUE TITLE
Zero-G turning head doesn't turn player orientation (messing up forward/back/left/right movement controls)

### ISSUE THREAD

**Issue by JpTiger** [Raicuparta/nomai-vr#382]
First of all, thank you for creating what is my favorite VR experience to date, hands down. It's absolutely incredible and I can't wait to get my headset on again for another run.

Now, I think I might be playing in a way that wasn't anticipated: I stand in the middle of a room and turn my whole body to face whatever direction I want to go (playing on a Quest with ReViveVR,  so no wires). I didn't even realize the right hand thumbstick did anything until my third or fourth loop (made piloting the spaceship fun). Which meant that, to take the least spoilery example possible, when I'm in the zero-g cave on timber hearth, if I physically turn myself 90 degrees to the left, pressing forward on the left stick moves me to my right, pressing left moves me forward etc. I have to keep looking down at the feet decals to figure out which way the game thinks I'm facing. This isn't an issue for environments where I'm walking, the game seems to track which way I'm facing just fine.

**Comment by Raicuparta** [comment]
This is a technical limitation with how the player physics behave in zero G vs while standing on a planet. Too much work to fix.

**Comment by JpTiger** [comment]
That seems totally fair. Would it be worth considering adding a input to in zero g (and spaceflight) for "right stick- turn" or similar? I think there's something there for grip+right stick - roll already, perhaps that could just be modified to include right and left turning?

**Comment by Raicuparta** [comment]
@JpTiger not sure what you mean. Right and left turning already works in Zero G. It's just always relative to the character's "forward" direction. To know the forward direction in zero-g, either look at the compass present in the helmet HUD (there's a longer line pointing forward), or look at the player's footprints.

**Comment by JpTiger** [comment]
Sorry I wasn't clear, when I said "input" I meant a visual HUD prompt when in zero-g next to the right hand indicating that the right stick can rotate the player.

**Comment by Raicuparta** [comment]
Fixed in #391, available now in update 1.1.1
