### ISSUE TITLE
Full support for left handed player in the future?

### ISSUE THREAD

**Issue by Hoshi82** [Raicuparta/nomai-vr#405]
As topic says a full support would be nice, like using tools with left hand ect. Rebinding in SteamVR Controls is not that big of a problem but setting "interact with tools" to the left controller still needs to be picked up with the righ hand. :)

**Comment by Raicuparta** [comment]
It might be coming soon :) Not possible to give an estimation, but you can track the progress here: https://github.com/Raicuparta/nomai-vr/pull/404

Closing this issue since it's covered by #178
