### ISSUE TITLE
Rebind the ship map key from the left thumbstick click to any free button. 

### ISSUE THREAD

**Issue by officialnochill** [Raicuparta/nomai-vr#406]
* NomaiVR Version: 1.1.4
* VR hardware: Lenovo Explorer (applies to all WMR headsets except G2)

Upon boarding the space ship, WMR users will quickly realize that there is no map key and the tooltip shows up as [].
This is because it is bound to the left thumbstick click, the left and right thumbstick clicks are used to open the steamvr dashboard meaning you cannot open the map. 

Ideally this should be bound to any free space on the WMR controller such as DPAD click down.

**Comment by officialnochill** [comment]
Would like to add that if the entire left DPAD is set as one button you will have to break it up into multiple, whenever possible, avoid multi-button combos and rather use the all 8 buttons the DPAD gives you access to

**Comment by artumino** [comment]
It should be addressed in the new release, going to leave this open until we have some form of confirmation

**Comment by officialnochill** [comment]
Alright the new buttons work, however, they do not show up as a tooltip in game (no map button tooltip shows up in the cockpit) and the mark on hud button just shows up as "Right trackpad click" instead of "Right trackpad North"

**Comment by Raicuparta** [comment]
The ambiguous track pad prompt might be a limitation of how SteamVR reports the bindings, not sure if it's fixable... @artumino any ideas? I think i had this issue before so just used the whole track pad as one button at some point?

**Comment by artumino** [comment]
Yes, dpad actions aren't returned properly from OpenVR. I still think it's better to have them as dpad actions though. Maybe I can try and open an issue in the OpenVR repo...

As for the map prompt it still appears as []? Only in the cockpit or is it like that even while wearing the suit?

**Comment by artumino** [comment]
Someone else already pointed this out, doesn't seem like there's any fix in sight :|

https://github.com/ValveSoftware/openvr/issues/1017

**Comment by Raicuparta** [comment]
Are we using the broken bindings in any of the defaults? If not then I'm fine with ignoring this... If we are using it in the defaults, then we need to change it...

**Comment by artumino** [comment]
We are binding dpad actions to the trackpad for the wands and old WMR. On WMR it's done cause there are no other possible bindings, on wands I added it cause there was no binding for the menu button.

In both cases it's always limited to North and South with south always being the back button and north Jump/Menu/Map based on the controller. So those prompts will both appear as "Click trackpad".

**Comment by officialnochill** [comment]
> Yes, dpad actions aren't returned properly from OpenVR. I still think it's better to have them as dpad actions though. Maybe I can try and open an issue in the OpenVR repo...
> 
> As for the map prompt it still appears as []? Only in the cockpit or is it like that even while wearing the suit?


The map prompt does not appear at all since the new update

**Comment by officialnochill** [comment]
Also using some workarounds its possible to get both the Joystick click to work in game as well as not disable the SteamVR dashboard so for some people the old bind may work?

**Comment by artumino** [comment]
> 
> 
> > Yes, dpad actions aren't returned properly from OpenVR. I still think it's better to have them as dpad actions though. Maybe I can try and open an issue in the OpenVR repo...
> > As for the map prompt it still appears as []? Only in the cockpit or is it like that even while wearing the suit?
> 
> The map prompt does not appear at all since the new update

Nothing regarding prompts visibility was changed in the update, we are not really messing with the game on that front (a part from disabling the ones that aren't relevant to VR like buttons to extract/holster tools). If I remember correctly the open map prompt is only shown when the ship is landed somewhere, as soon as you takeoff it gets hidden. Are you sure it isn't displayed while on the launch pad?

**Comment by Raicuparta** [comment]
Also, there's an option in the game itself (not a mod option) that disables most prompts

**Comment by officialnochill** [comment]
> > > Yes, dpad actions aren't returned properly from OpenVR. I still think it's better to have them as dpad actions though. Maybe I can try and open an issue in the OpenVR repo...
> > > As for the map prompt it still appears as []? Only in the cockpit or is it like that even while wearing the suit?
> > 
> > 
> > The map prompt does not appear at all since the new update
> 
> Nothing regarding prompts visibility was changed in the update, we are not really messing with the game on that front (a part from disabling the ones that aren't relevant to VR like buttons to extract/holster tools). If I remember correctly the open map prompt is only shown when the ship is landed somewhere, as soon as you takeoff it gets hidden. Are you sure it isn't displayed while on the launch pad?

Doesn't show up before takeoff either, just gone

**Comment by officialnochill** [comment]
Also the roll button in ship shows up as Palm Trigger + Righthand joystick CLICK, is that actually the button? 
Doesn't seem to do anything

**Comment by Raicuparta** [comment]
> Also the roll button in ship shows up as Palm Trigger + Righthand joystick CLICK, is that actually the button?
> Doesn't seem to do anything

Hm no, it's trigger + joystick move. I remember that the way I differentiated between click and move was also a bit hacky, again due to issues with OpenVR not reporting the full input names. So probably related to that.

**Comment by artumino** [comment]
@Raicuparta maybe we can just check if the SteamVR is a SteamVR_Action_Boolean to add the "Click" prefix instead of doing it the current way?

**Comment by artumino** [comment]
I pushed a proposal in #413
Instead of checking the type I added an arguement to the actioninput constructor. Was to other check there to avoid setting these manually?

I avoided marking the interact button and the roll button as clickable cause in some instances they are press and hold buttons.

**Comment by officialnochill** [comment]
To elaborate further after some testing you CAN use the signalscope, the button prompt just does not mention that the correct bind is right hand palm trigger + click right trackpad. 
![Desktop Screenshot 2021 05 26 - 12 16 43 49](https://user-images.githubusercontent.com/63358288/119643994-b336b200-be1c-11eb-9c38-12e6820e8122.png)

Secondly, you can also roll, the correct bind is to hold left palm trigger then move the right analog stick though it isn't very clear either. 
![Desktop Screenshot 2021 05 26 - 12 16 21 53](https://user-images.githubusercontent.com/63358288/119644255-f55ff380-be1c-11eb-808b-d17e0b8248bb.png)

The clarity of the game controls when using the old thumbsticks binds were pretty good if you know how to bypass it opening the steamvr dashboards.

**Comment by Raicuparta** [comment]
@artumino Yeah it seems like something's wrong with the prompts. Seems like when I pick up a tool with my left hand, it says just "Grip", but with my rand hand it says "Right hand grip". When I tried using the probe launcher in the ship, at first it said just "Grip + Click" or something like that, missing some words. Seems like a tricky thing to get working perfect.

**Comment by artumino** [comment]
@Raicuparta I have a branch open where this should be fixed, I'll open up another pull request. As always with the way SteamVR action sets work you have to enable them to generate the prompts and then disable them so it's a bit of a mess...
Should work fine now

I also bound the roll toggle to both grip buttons on Oculus, WMR and Wand controllers it should prevent the "Grip" action to switch between "Right Hand Grip" or "Grip"

**Comment by artumino** [comment]
Version 1.2.1 has all the improvements we talked about, give it a try if you can

**Comment by officialnochill** [comment]
Tried out the new version and all is fixed! 

Now the only request would be to have an alternate version where it uses joystick click for clearer prompts as I perhaps hand off the game to a friend to try after disabling the SteamVR dashboard and letting the no joystick be the default of course.
