### ISSUE TITLE
Probe Launcher just not functioning sometimes

### ISSUE THREAD

**Issue by officialnochill** [Raicuparta/nomai-vr#417]
NomaiVR Version: 1.2.1
VR hardware: Lenovo Explorer (WMR)
 
 I am not sure what triggers this bug but when I take pictures with the probe launcher, nothing shows up on the screen. 
 If this bug occurs I think it persists restarts of the loop because it seems like it did for me, rendering the mechanic unusable until 
 the game is restarted. 

![Desktop Screenshot 2021 05 27 - 17 53 15 55](https://user-images.githubusercontent.com/63358288/119900364-ba58df80-bf44-11eb-9f4a-5cf46db2cc3d.png)
![Desktop Screenshot 2021 05 27 - 17 52 41 41](https://user-images.githubusercontent.com/63358288/119900374-bcbb3980-bf44-11eb-87f1-8c3e44ab1769.png)

**Comment by Raicuparta** [comment]
Should be fixed since 2.0.0
