### ISSUE TITLE
The controls for the various things in your belt are... difficult

### ISSUE THREAD

**Issue by NSExceptional** [Raicuparta/nomai-vr#419]
For example, when you pull out the scout launcher, the JOYSTICK is bound to something? Why? This means I cannot move the camera while I have the scout launcher out... I think a good replacement would be clicking the joystick instead. If it is possible to remap that without messing up the other controls, I will try that, but it is not, to my knowledge

**Comment by Raicuparta** [comment]
Closing this in favor of #465
