### ISSUE TITLE
Recenter Button 

### ISSUE THREAD

**Issue by FolkSong** [Raicuparta/nomai-vr#420]
I just started playing the game, and noticed a frequent annoyance when you interact with something that isn't straight ahead of you. The right joystick gets disabled so you can't fix the view, and if you're sitting in a non-rotating chair you can't physically fix it, so you have to keep your head turned awkwardly. When in the ship it's tempting to point towards the screen on the right when first activating it, which locks your view that way instead of straight out the window. I even had situations on the planet where something happened behind me, causing the game to show a "look here" arrow, and I had to twist around to see what was going on.

Presumably there is a "default" direction that the non-VR game uses, so my request is to map a button or combo to snap your current view to that direction in the horizontal plane.

**Comment by Raicuparta** [comment]
There should be a recenter VR option in the pause menu. Do you see it? Other than that, yeah, the "look" arrows are the solution to not wanting to move the camera against the user's will. I won't implement any other alternative, but I'll leave this issue open in case anyone is interested in helping.

**Comment by FolkSong** [comment]
I checked out the menu item, but it doesn't help for a couple reasons. Firstly, I can't always access the menu, for example when in dialog. But even when I can, the option doesn't seem to do anything. Even if I look in a different direction and hit the recenter button, nothing changes when I exit the menu, the world orientation relative to my chair is the same.

After playing some more I don't think it's a big deal, other than the occasional annoyance when someone calls out to me from behind and I have to twist around to see them.

Actually the bigger issue is using tools and not being able to move or rotate, depending on which hand the tool is in. It makes for a tedious process of dropping the tool every time I need to move or turn. Then again maybe it's like that in the non-VR game too, I haven't tried it.

Anyway, I'll close this.
