### ISSUE TITLE
Is it possible to disable/toggle the hand laser/interaction laser in the settings?

### ISSUE THREAD

**Issue by importedturtle** [Raicuparta/nomai-vr#421]
I love this mod so much, it really is amazing and turns Outer Wilds into a native VR game. It's as good as an official version as it can get, so thanks for your work on it. However as I mentioned in the title would this be possible? I personally find this laser distracting, and same with the feet markers. I would love the option to toggle these in the settings.

**Comment by importedturtle** [comment]
For me I just feel like it would make the game even more immersive. This is the only thing that I wish was in the mod, everything else is perfect and all I could ask for in terms of a VR version of Outer Wilds :)

**Comment by artumino** [comment]
Introduced in #422 👍
