### ISSUE TITLE
Compatibility with openvr_fsr (AMD FidelityFX SuperResolution for VR)

### ISSUE THREAD

**Issue by Akimya49** [Raicuparta/nomai-vr#424]
Hi There, 

@fholger made a modified openvr_api.dll that allows you to apply FidelityFX SuperResolution upscaling to many SteamVR games, as long as they use D3D11 (https://github.com/fholger/openvr_fsr).

I've runned a few successfull testing on nomai VR and it seems to improve performance greatly (cost a bit of image quality, but still totally worth imo)

I had to put openvr_api.dll on read only since it seems to be erased each time when you start nomaiVR. 

I'm playing on an Oculus Quest 2 with Air link (4128x2096 / 90Hz) on an R5 3600 / RTX 2080 / Medium settings in game

Without FidelityFX > 33fps : 
![OculusScreenshot1628367726](https://user-images.githubusercontent.com/46827872/128613207-5cffac90-5acb-4cc8-85dd-0af9a22fffa3.jpeg)

With FidelityFX (quality) > 45fps : 
![OculusScreenshot1628367570](https://user-images.githubusercontent.com/46827872/128613216-4ab14b58-b367-4228-84a4-749ce2a8b8db.jpeg)

With FidelityFX (performance) > 80+fps : 
![OculusScreenshot1628367398](https://user-images.githubusercontent.com/46827872/128613198-0442a356-7e91-414b-a143-615b39d1a261.jpeg)

Would be really nice to merge this into nomai VR ! 
Thanks for the mod anyway :)

Regards.

**Comment by Raicuparta** [comment]
Yeah I've also tried it and it works great. I might try to include it, but I'd want to figure out a way for people to configure the resolution in-game. I've been busy with the Firewatch VR mod, but maybe when I come back to Outer Wilds for the DLC I can try to figure this out.

**Comment by matejdro** [comment]
It would be helpful if you would specify where to put the DLL. I know it normally goes into Plugins folder for Unity games, but this is a mod, so I assumed it would be different

I found 3 possible locations:

1. `OWML\Mods\Raicuparta.NomaiVR` (no openvr dll originally, but it is main mod folder and there was another Valve-named dll, so this was my first though. No dice)
2. `OWML\lib` (this one had openvr dll in it, but replacing it did not appear to do anything)
2. `steamapps\common\Outer Wilds\OuterWilds_Data\Plugins` (replacing this dll actually did the trick)

**Comment by Raicuparta** [comment]
Added in #460
