### ISSUE TITLE
Crashes instantly, also corrupts 3 game files

### ISSUE THREAD

**Issue by MeepDaSheep** [Raicuparta/nomai-vr#436]
* Game Version: 
* OWML Version:
* NomaiVR Version:
* VR hardware:

 
<html>
<body>

* Raicuparta.NomaiVR v1.2.3 | OWML |  
-- | -- | --
Adding patch in PermanentManager.Awake. | OWML |  
Raicuparta.NomaiVR requires VR. | OWML |  
Error while applying VR patch: System.Exception: Could not find patch zone in globalgamemanagers. This probably means the VR patch needs to be updated. at OWML.Patcher.VRFilePatcher.FindPatchStartOffset(Byte[] sectorBytes) in D:\a\owml\owml\src\OWML.Patcher\VRFilePatcher.cs:line 53 at OWML.Patcher.VRFilePatcher.Patch() in D:\a\owml\owml\src\OWML.Patcher\VRFilePatcher.cs:line 31 at OWML.Patcher.VRPatcher.PatchVR(Boolean enableVR) in D:\a\owml\owml\src\OWML.Patcher\VRPatcher.cs:line 32 at OWML.Launcher.App.PatchGame(IList`1 mods) in D:\a\owml\owml\src\OWML.Launcher\App.cs:line 134

this is the log

</body>
</html>

**Comment by Raicuparta** [comment]
fill in the requested details before reopening
