### ISSUE TITLE
[SPOILER] A certain means of transport in the DLC has some issues when translated to VR

### ISSUE THREAD

**Issue by artumino** [Raicuparta/nomai-vr#439]
The travel totems rely on changing the camera FOV to give the illusion of not moving while travelling to the destination. This works in VR if the player is looking straight at the totem but quickly breaks if he's looking just a few degrees off the totem.

The fov change can be disabled and this will give the feeling of a dash instead.

The current fix implements the same effect present in the flat game by using the XRDevice.fovFactor but introduces another bug where if the user goes in the pause menu mid transition it'll have the zoomed in fov (quickly fixable though)

Since there seem to be only a handfull of instances of this type of movement we could evaluate:

1. Leaving the current system in if we deem it survivable for the few 2 second transitions the player will do (and fix the few bugs it introduces)
2. Remove the fov change and just leave the dash (but somewhat loose the general feel of the original mechanic)
3. Implement something of our own like for example the [Budget Cuts teleport effect ](https://youtu.be/f786ak3GKQo?t=104)

Since this is foundamental mechanic of the DLC at least 1 or 2 should be implemented for 2.0.0

**Comment by artumino** [comment]
As of the latest commit on 2_0_0 the bug with going into the menu/restarting the loop/exiting the dream mid transition should be fixed

Having finished the DLC I can confirm that there are a small number of these throughout the DLC so we could actually leave the effect as is

**Comment by Raicuparta** [comment]
It's perfect now
