### ISSUE TITLE
Pressing right trigger while not wearing spacesuit makes player lose ability to jump

### ISSUE THREAD

**Issue by AnthonyCuviello** [Raicuparta/nomai-vr#467]
* Game Version:  1.1.11.72
* OWML Version: 2.1.0
* NomaiVR Version: 2.3.1
* VR hardware: Oculus Quest 

 When you aren't in your spacesuit pressing right trigger at any point makes you lose your ability to jump until you die (you can still use thruster while in spacesuit). This effect carries over to the (spoiler) parts of the dlc. I tested it and it happened each time and at every location.

**Comment by Raicuparta** [comment]
Sensitivity issue? Your trigger is being detected as being pressed so the game ignores the jump press (that's a base game thing). We generally have issues with sensitivity in analog controls for some reason. You can try going to SteamVR controller bindings and changing the sensitivity for that trigger.
