### ISSUE TITLE
Probe cannon explosion is not naturally visible when player awakens

### ISSUE THREAD

**Issue by SaberMage** [Raicuparta/nomai-vr#468]
One of the core experiences in the pancake game is waking up facing the sky, which instills curioustiy regarding the probe cannon, giant's deep, and potentially the quantum moon. Some solution for this would be much appreciated.

Idea: add a small, reflective puddle of water (or ice shard i.e what's on The Attlerock) near the launchpad elevator which reflects the sky, including Giant's Deep's starting location.

**Comment by Raicuparta** [comment]
I actually have a solution for this which I Implemented before 2.0, and it works pretty well: changing Timber Hearth's initial rotation so that Giant's Deep will be visible without looking up. I just didn't test it deeply enough and never updated that change to NomaiVR 2.0.

The reflection thing wouldn't really be feasible.

**Comment by WolfKitJ** [comment]
Maybe you could make it such that the 'Wake up' prompt which tells one to look at their main hand and press B, also tells them to look straight up?

**Comment by Raicuparta** [comment]
Rotating TH already seems like the perfect solution to me. That prompt serves ti teach VR players that I puts show in their hands so I don't wanna mess with it

**Comment by WolfKitJ** [comment]
My perspective is that I'd rather see NomaiVR be as close to the base experience as possible, and I think that encouraging players to look up (where the base game starts looking up) serves that goal better than rotating Timber Hearth (changing optimal launch flight paths).

If you do change Timber Hearth's rotation, could you add a setting to leave it unchanged?

**Comment by Raicuparta** [comment]
Probably not, there's too many options as it is. I even discussed this with one of the devs of Outer Wilds and they agreed that it's the best solution so if we do anything about it it will definitely be by rotating the planet. People who play I'm VR for the first time wouldn't even know anything is different
