### ISSUE TITLE
Stuck on main menu

### ISSUE THREAD

**Issue by GiBg1aN** [Raicuparta/nomai-vr#486]
* Game Version: 1.1.11
* OWML Version: 2.2.0
* NomaiVR Version: 2.4.2
* VR hardware: Oculus quest 2

Hello everyone, I've tried this mod a month ago (I think version 2.2.0) just to try if my PC could handle it and it worked pretty good for half an hour. Today i updated it to start my first OW run for real. Unfortunately I am stuck on the main menu. I tried to uninstall the mod, verify game files and reinstall it (and theatre mode is already off).

My steps to reproduce the problem are the following:
1. Connect VR headset
2. Go in "PCVR mode" through oculus link
3. Open OW mod manager
4. Press on start game (with the mod ticked)
5. Start the game via Steam (not steam VR)

Starting the game via the mod manager just opens a black window which disappears immediately, then I start the game via steam, which starts steamvr and loads the game.

The behaviour is the following:

The music starts, but "Annapurna" and the other writings "on the stars" appear on the left (I have to turn my head by 90 degrees to the left) and are rotated by 45 degrees. Then Outer Wilds title is shown, but I can only see the final "D" and "S" (and a partial "L) and if I move my head it is fixed to it. Here attached you can find a screenshot (the screenshot is clearly wider than my fov, so guess that it is cropped at the centre). After that I can't see the menu. My monitor is showing a mirrored image of my headset during the loading I then when the (partial) title appears in the headset, the monitor displays the menu as the vanilla game. I tried to interact with it with the mouse with no result.

I tried to start the game both via steam, steam vr and oculus home with the same result.

I tried to be as much detailed as possible I hope to be useful.

Thank you for your amazing mod and thank you in advance for helping me.

![OculusScreenshot1637701232](https://user-images.githubusercontent.com/5871979/143133104-00c2dfef-2b9b-4037-b976-87170a93be8a.jpeg)

**Comment by Raicuparta** [comment]
Show the logs in the mod manager

**Comment by GiBg1aN** [comment]
Eventually it worked uninstalling and reinstalling the mod manager. Thank you anyway for answering!
