### ISSUE TITLE
Link to AssemblyPublicizer is dead

### ISSUE THREAD

**Issue by farmboy0** [Raicuparta/nomai-vr#497]
The link is used in SETUP.md
It points to https://github.com/Raicuparta/AssemblyPublicizer/releases which doesn't exist anymore.

**Comment by Raicuparta** [comment]
Ah, sorry about that. The setup documentation is really outdated, the publicizer isn't needed anymore since NomaiVR has a Nuget dependency that includes the publicized dlls already. I'll try to update that documentation asap.

**Comment by Raicuparta** [comment]
I have updated those instructions now, hopefully it's clear enough. I'm not sure if all required steps are documented there, just let me know if you face any other issues.
