### ISSUE TITLE
Stuck on loading screen forever - PC gamepass 

### ISSUE THREAD

**Issue by bfbarkhouse** [Raicuparta/nomai-vr#499]
* Game Version: 1.1.11.114
* OWML Version: 2.3.0
* NomaiVR Version: 2.6.0
* VR hardware: Oculus Quest 2
* Game store: Xbox PC Gamepass

I followed all the steps to enable this mod with the gamepass version outlined in the readme. When I launch the game, the credit sequence starts as expected but then the loading screen just runs forever. To be clear by loading screen I mean that I see the title and to the right there is a little campfire world and a moon icon indicating its trying to load. The game never progressed past this. There is an error in the logs but I can't determine what the problem is. Debug logs below:

Started console server on port 64076 | Mod Manager |  
Client connected to console | Mod Manager |  
Started OWML v2.3.0 | OWML |  
Current game path is not valid: C:/Program Files (x86)/Steam/steamapps/common/Outer Wilds | OWML |  
Game not found in Steam. | OWML |  
Game not found in EGS. | OWML |  
Game found in C:\Program Files\WindowsApps\AnnapurnaInteractive.OuterWilds_1.11.114.0_x64__c96c51jf6wkvm | OWML |  
Game version: 1.1.11.114 | OWML |  
Game version is supported | OWML |  
Game files copied. | OWML |  
Found mods: | OWML |  
Raicuparta.NomaiVR v2.6.0 | OWML |  
Copying OWML files... | OWML |  
Copying replacement OW files... | OWML |  
Patching OW assembly... | OWML |  
Executing patcher for Raicuparta.NomaiVR v2.6.0 | OWML |  
Identified as an Xbox Game Pass install. Launching... | OWML |  
Client disconnected from console | Mod Manager |  
Client connected to console | Mod Manager |  
Mod loader has been initialized. | OWML |  
Game version: 1.1.11.114 | OWML |  
**Error - method ProfileMenuManager.PopulateProfiles not found. | NomaiVR |  
Error in Patch: original MethodInfo is null. | NomaiVR |**  
Client disconnected from console

**Comment by Raicuparta** [comment]
That's because Xbox login failed. Try launching the game from the Xbox launcher, and don't skip intro logos. Also remember to take off your headset so you can log in to Xbox the first time. Following times you shouldn't have to do this.

**Comment by bfbarkhouse** [comment]
That worked like a charm thank you very much. Perhaps you could add this caveat to the readme?

**Comment by Raicuparta** [comment]
Glad it worked. Added some info to the readme.

**Comment by fireguy908** [comment]
Hi there! I am having a similar issue to this. I am able to open the game and get all the way to the main screen where it shows me options like continue expedition, new game, options, etc., however the cursor just continues to be a spinning blue wheel and doesn't allow me to click on anything. Here is the launcher code log for reference:

Client connected to console | Mod Manager |  
-- | -- | --
Started OWML v2.3.2 | OWML |  
Game found in D:/Outer Wilds/Outer Wilds/Content | OWML |  
Game version: 1.1.11.114 | OWML |  
Game version is supported | OWML |  
Game files copied. | OWML |  
Found mods: | OWML |  
* Artum.NomaiVRFoveated v1.0.3 | OWML |  
* Raicuparta.NomaiVR v2.6.0 | OWML |  
Copying OWML files... | OWML |  
Copying replacement OW files... | OWML |  
Patching OW assembly... | OWML |  
- Assembly is already patched. | OWML |  
Executing patcher for Artum.NomaiVRFoveated v1.0.3 | OWML |  
Executing patcher for Raicuparta.NomaiVR v2.6.0 | OWML |  
Identified as an Xbox Game Pass install. Launching... | OWML |  
Client disconnected from console | Mod Manager |  
Client connected to console | Mod Manager |  
Mod loader has been initialized. | OWML |  
Game version: 1.1.11.114 | OWML |  
Error updating AppManifest: System.NullReferenceException: Object reference not set to an instance of an objectat NomaiVR.Helpers.ApplicationManifestHelper.UpdateManifest (System.String manifestPath, System.String appKey, System.String imagePath, System.String name, System.String description, System.Int32 steamAppId, System.Boolean steamBuild) [0x0005c] in <e4219433a66b401fb262aad68b496dd0>:0 | NomaiVR |  
NullReferenceException: Object reference not set to an instance of an objectStacktrace: NomaiVR.NomaiVR.InitSteamVR () (at <e4219433a66b401fb262aad68b496dd0>:0)NomaiVR.NomaiVR.ApplyMod () (at <e4219433a66b401fb262aad68b496dd0>:0)NomaiVR.Loaders.NomaiVRLoaderOwml.Start () (at <e4219433a66b401fb262aad68b496dd0>:0) | OWML |  
Start NomaiVRFoveated | NomaiVR Fixed Foveated Rendering |  
Loading asset bundle from C:/Users/chris/AppData/Roaming/OuterWildsModManager/OWML/Mods\Artum.NomaiVRFoveated\assets/foveated-shaders | NomaiVR Fixed Foveated Rendering |  
Creating NomaiVRFoveated behaviour for FoveatedRenderingEnabler | NomaiVR Fixed Foveated Rendering |  
  | OWML |  
Client disconnected from console | Mod Manager
