### ISSUE TITLE
camera hovering over player& no menu visible & drifting after wakeup

### ISSUE THREAD

**Issue by Kal-92** [Raicuparta/nomai-vr#500]
* Game Version: 1.1.12.125
* OWML Version:2.3.1
* NomaiVR Version:2.6.0
* VR hardware: Oculus Quest 2 via airlink & UsbLink

 worked fine on start menu.
1. no 'wakeup' UI shown on new game(Pressed random button on controller and proceed)

![image](https://user-images.githubusercontent.com/97718698/149450635-45e6d002-d6fa-439a-af01-20c0aabda0a4.png)
2. Drifting & camera floating issue happened.
3. no movement control& hand control available.
4. jump button(playing animation, not actually jumped) and turn around control & menu button is still available.

![image](https://user-images.githubusercontent.com/97718698/149456496-c3816b04-bf4d-4712-9c35-69e6b9bc1464.png)
5. time stopped and tinting is happened when pressing menu button(as supposed), but pause menu UI not visible.
(instead, pause menu UI is visible in desktop screen)
not sure what exactly wrong with my situation..

**Comment by Kal-92** [comment]
it solved!
![image](https://user-images.githubusercontent.com/97718698/149458686-ec6352d9-04b3-4bc2-b45a-6c45e966a655.png)
i don't even know how this mod stuck in my modlist..
disable that and everything is going smooth!

**Comment by Raicuparta** [comment]
Oh, OWO is supposed to be compatible with NomaiVR, so that's strange. I'll look into it, thanks.
