### ISSUE TITLE
Holding the grip button causes the player to walk slowly, and slow down to almost a standstill at edges.

### ISSUE THREAD

**Issue by officialnochill** [Raicuparta/nomai-vr#513]
The issue is caused by the "roll" bind, which is also bound to a walk in code. 
This behavior is present in the base game, but it is a bigger issue in NomaiVR, where certain puzzles require you to have your scout launcher equipped by pressing the grip button, which is also bound to roll.

Video demonstration of the bug here:
https://user-images.githubusercontent.com/63358288/175876105-b99de8cd-82e9-4d7c-aa52-cbf59688acdc.mp4

A comparison between a hand with roll unbinded and one with roll bound to grip.

https://user-images.githubusercontent.com/63358288/175876445-0419f6f5-00a5-44ad-9ae2-a65bf406438d.mp4

Potential Fix: Disable the roll bind on the hand that is currently holding a tool.

**Comment by Raicuparta** [comment]
Forgot to close this, it was fixed in 2.7.0
