### ISSUE TITLE
Cannot get vr to function **FIXED

### ISSUE THREAD

**Issue by outestwilds** [Raicuparta/nomai-vr#515]
I'll start with the errors that pop up and then explain what happens, what I can do and what I can't do.

![Screenshot (2)](https://user-images.githubusercontent.com/108971128/178094788-1153570d-852d-441f-9237-f10c2ba952d7.png)

<b>[SteamVR]</b> Initialization failed. VR may be disabled in player settings. Go to player settings in the editor and check the 'Virtual Reality Supported' checkbox'. To attempt to force OpenVR initialization call SteamVR.Initialize(true).

for this, I went into properties on steam (i have the game +dlc on epic but bought it again on steam because i had hope that it would work with steam, still no luck) and i added "SteamVR.Initialize(true)" into the launch options.  hasn't seemed to change anything.  I've also changed this in a few other settings accessible on steam that people talk about on other question forums.

Error updating AppManifest: System.NullReferenceException: Object reference not set to an instance of an object
at NomaiVR.Helpers.ApplicationManifestHelper.UpdateManifest (System.String manifestPath, System.String appKey, System.String imagePath, System.String name, System.String description, System.Int32 steamAppId, System.Boolean steamBuild) [0x0005c] in <15dd35e5c7224efc93d83138a6834d0a>:0

for this, i have no clue.  I downloaded some unity program but I can't seem to access it.  I doubt I even needed to download it.  I have no clue how to set an object as reference on the programs I have at my disposal.

Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues.

I have no clue how to go about setting the parent or whatever its asking, or if this even matters.

anyways, I have the quest 2 airlink thing going on, i open desktop mode on the quest 2, and launch the game from the mod manager.  It opens two copies of like, just regular old rectangles of the game, one stationary, and one i can drag around.  I have no ability to control anything, i get a spinning wheel of death that doesn't spin.  To rephrase this, I'm stuck on the title screen.  cant even touch anything.

I've touched all sorts of settings but i have absolutely no clue what im doing or why this is happening.  this is so simple but everything i touch breaks.  If anyone has any insight I would appreciate it.

**Comment by outestwilds** [comment]
I found out what I was missing!  I hope this helps anyone who was having issues like mine.

I didn't have the steam vr application installed on my computer!   It was really that simple.  I was even able to return my second copy of outer wilds on steam, steam vr works perfectly fine with epic.  weird, right?

**Comment by Kean4711DUB** [comment]
Thank You. New to PCVR and VR in general so this was a huge help.

**Comment by outestwilds** [comment]
> Thank You. New to PCVR and VR in general so this was a huge help.

I'm so glad I could help someone!  leave another comment here if you need anything.  it's been a while since I was last active with vr but I can probably help you if anything weird happens.  have a lovely new year! 🩷
