### ISSUE TITLE
Patches don't support gamepass differences

### ISSUE THREAD

**Issue by misternebula** [Raicuparta/nomai-vr#518]
* Game Version: 1.1.12.181
* OWML Version: 2.5.2
* NomaiVR Version: 2.7.0
* VR hardware:

The gamepass version of the game has a lot of differences in how it loads profiles/saves.
In the patches in Menus.cs, this method does not exist in the gamepass version.
https://github.com/Raicuparta/nomai-vr/blob/920a0ede4c61a95e82497d003985fe0ac0b463df/NomaiVR/UI/Menus.cs#L323

**Comment by Raicuparta** [comment]
This doesn't affect the mod so probably won't be fixed.

**Comment by Raicuparta** [comment]
gonna close this because let's be honest nobody is gonna fix it
