### ISSUE TITLE
Jank/Shaky HUD Elements & Dark Bramble

### ISSUE THREAD

**Issue by Jankunofficial** [Raicuparta/nomai-vr#525]
* Game Version: Build ID: 9486925
* OWML Version: 2.6.0
* NomaiVR Version: 2.8.4
* VR hardware: Oculus (forever) quest 2

When playing in VR mode, I have noticed that certain HUD elements, such as the ship marker and waypoints in general, will shake quite a bit-- particularly if you move your head around a lot. The problem seems to be largely based around head motion. Unfortunately, I am not able to attach a screenshot or video as for some strange reason the flatscreen view of the VR gameplay did not show the bug. Also, for some strange reason, the shakiness described above also applies to the node lights in Dark Bramble when they are still covered in fog. If I am able to capture footage of the issue, I will attach a comment to this post.

Also, as a small side note related to HUD, it seems to me that the current implementation is extremely hard to see comfortably. Either a HUD size scaling option or some kind of hand-based implementation of the stats like HL:Alyx has would probably be beneficial.

**Comment by Raicuparta** [comment]
HUD already discussed in #321

HUD scale option is already there.

Closing this.

**Comment by Jankunofficial** [comment]
my bad. Will look into it more carefully next time
