### ISSUE TITLE
Automatically initated conversations can cause the player to clip through the ground

### ISSUE THREAD

**Issue by Z5aI69A61** [Raicuparta/nomai-vr#96]
Automatically initiated conversations such as the ones after the first statue pairing upon exiting the museum seem to reset the player's position and gravity, and can cause the player to clip through the ground.

**Comment by Raicuparta** [comment]
Did you clip to the ground before, during, or after the conversation was done? Did this happen in the latest version of NomaiVR?

**Comment by Z5aI69A61** [comment]
This occurred immediately after the conversation finished. It's also worth noting that I use the option to disable time while in conversations. And, yes, this was the latest version.

**Comment by Raicuparta** [comment]
@Z5aI69A61 I just uploaded a new version (0.18) that by default disables the ability to move the player body by moving the VR headset. It's very hard to get this behavior to work without bugs so I'm disabling it by default for now (can be enabled in config.json). Please let me know if the latest update prevents this bug. And please confirm that your config.json file (inside NomaiVR directory) has the setting `"movePlayerWithHead": false,`.

**Comment by Z5aI69A61** [comment]
@Raicuparta The bug still occurs with the setting disabled. Strangely, the dialogue actually seems to flip me on my side. It was hard to tell before, but this time it happened just as the conversation started, instead of ended, leaving me on my side through the whole thing.

**Comment by Raicuparta** [comment]
Maybe you were just sleepy?

I'll look into it, thanks for the report!

**Comment by Raicuparta** [comment]
@Z5aI69A61 I can't seem to reproduce this in 0.18... Any chance you could record a video of it happening? Thanks.

**Comment by Z5aI69A61** [comment]
@Raicuparta  
https://youtu.be/gwUc-rEpuws  
There you go. It happens every time for me.

**Comment by Raicuparta** [comment]
@Z5aI69A61 thanks, this is very helpful!

**Comment by Raicuparta** [comment]
Hi @Z5aI69A61 

Any chance you could check if this issue is fixed in version 0.38? I added a system that completely disables the game's ability to lock the camera to stuff, so I think this shouldn't happen anymore.

**Comment by Raicuparta** [comment]
New info: related to time freeze settings:
> It doesn't happen if I disable the time stop during conversations, but it DOES still happen with the initial statue sync in the museum, I assume because that stops time regardless.
